# Generated by Django 6.0.4 on 2026-05-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='_state',
            new_name='state',
        ),
    ]
