# Generated by Django 6.0.4 on 2026-05-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename__state_room_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('booked', 'booked'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
