# Generated by Django 6.0.4 on 2026-05-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='availability_status',
            field=models.CharField(choices=[('open', 'Open'), ('booked', 'Booked'), ('unavailable', 'Unavailable')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('booked', 'booked'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
    ]
